version = 5.6.0
archive_dir = /etc/letsencrypt/archive/bot.storeconsole.com
cert = /etc/letsencrypt/live/bot.storeconsole.com/cert.pem
privkey = /etc/letsencrypt/live/bot.storeconsole.com/privkey.pem
chain = /etc/letsencrypt/live/bot.storeconsole.com/chain.pem
fullchain = /etc/letsencrypt/live/bot.storeconsole.com/fullchain.pem
[renewalparams]
account = bb726b171fedf0627d59a070b10e1326
config_dir = /etc/letsencrypt
work_dir = /tmp/letsencrypt-work
logs_dir = /tmp/letsencrypt-logs
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
bot.anichur.com = /var/www/certbot
bot.storeconsole.com = /var/www/certbot
