version = 5.6.0
archive_dir = /etc/letsencrypt/archive/focus-backend.anichur.com
cert = /etc/letsencrypt/live/focus-backend.anichur.com/cert.pem
privkey = /etc/letsencrypt/live/focus-backend.anichur.com/privkey.pem
chain = /etc/letsencrypt/live/focus-backend.anichur.com/chain.pem
fullchain = /etc/letsencrypt/live/focus-backend.anichur.com/fullchain.pem
[renewalparams]
account = bb726b171fedf0627d59a070b10e1326
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
focus-backend.anichur.com = /var/www/certbot
focus-frontend.anichur.com = /var/www/certbot
focus-web.anichur.com = /var/www/certbot
