version = 5.6.0
archive_dir = /etc/letsencrypt/archive/storeconsole.com
cert = /etc/letsencrypt/live/storeconsole.com/cert.pem
privkey = /etc/letsencrypt/live/storeconsole.com/privkey.pem
chain = /etc/letsencrypt/live/storeconsole.com/chain.pem
fullchain = /etc/letsencrypt/live/storeconsole.com/fullchain.pem
[renewalparams]
account = bb726b171fedf0627d59a070b10e1326
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
local.storeconsole.com = /var/www/certbot
