<?php
echo "INTELLIGENCE_PROVIDER=" . (getenv("INTELLIGENCE_PROVIDER") ?: "NOTSET") . "\n";
echo "INTELLIGENCE_EMBEDDING_PROVIDER=" . (getenv("INTELLIGENCE_EMBEDDING_PROVIDER") ?: "NOTSET") . "\n";
echo "INTELLIGENCE_EMBEDDING_DIMENSIONS=" . (getenv("INTELLIGENCE_EMBEDDING_DIMENSIONS") ?: "NOTSET") . "\n";
