[storeconsole-dev]
user = www-data
group = www-data
listen = /run/shared-php-fpm/storeconsole-dev.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
pm.max_requests = 500
pm.process_idle_timeout = 30s

chdir = /opt/apps/storeconsole-dev/codes

clear_env = no

php_flag[display_errors] = off
php_admin_value[error_log] = /var/log/php-fpm/storeconsole-dev.log
php_admin_flag[log_errors] = on
