bind 0.0.0.0
port 6379
protected-mode yes
timeout 0
tcp-keepalive 300
daemonize no
supervised no
loglevel notice
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
save 900 1
save 300 10
save 60 10000
maxmemory 1280mb
maxmemory-policy allkeys-lru
databases 16
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
