[program:storeconsole-staging-horizon]
command=php /opt/apps/storeconsole-staging/artisan horizon
directory=/opt/apps/storeconsole-staging
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/storeconsole-staging-horizon.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=3600
