[program:storeconsole-production-horizon]
command=php /opt/apps/storeconsole-production/artisan horizon
directory=/opt/apps/storeconsole-production
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/storeconsole-production-horizon.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=3600

[program:storeconsole-production-ssr]
command=php /opt/apps/storeconsole-production/artisan inertia:start-ssr --runtime=node --no-interaction
directory=/opt/apps/storeconsole-production
environment=SSR_ENABLED="true",SSR_URL="http://127.0.0.1:13714"
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/storeconsole-production-ssr.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=10
